name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # Veja o cronograma de versões suportadas do Node.js em https://nodejs.org/en/about/releases/

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Checkout do repositório
      - uses: actions/checkout@v4

      # Configurar a versão do Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      # Instalar dependências usando Yarn
      - name: Install dependencies
        run: yarn install

      # Configurar variáveis de ambiente para testes
      - name: Set environment variables
        run: echo "DATABASE_URL=postgres://test_user:test_password@localhost:5432/test_db" >> $GITHUB_ENV

      # Executar migrações do TypeORM
      - name: Run TypeORM migrations
        run: yarn typeorm migration:run

      # Construir o projeto
      - name: Build project
        run: yarn build

      # Executar testes
      - name: Run tests
        run: yarn test
